feat(Services-Communication): connected frontend and backend
CuisineCoders/tastybookmarks pull request #26
Opened 2024-10-13 15:58 UTC by Jan0H0Punkt

2024-10-19 17:46 UTC, crookoo commented on frontend/src/app/recipe/model/recipe.ts
In the frontend we label it "imageUrl", in the backend simply "image". It needs to be the same to work.

2024-10-19 17:47 UTC, crookoo requested changes
One important thing to change: imageUrl/image should be the same in frontend and backend. 

Other issues that could go into another task:
- Once a recipe is added it would be good to see the added recipe in the list. Now a manual refresh is needed to see the new recipe inserted into the list.
- I would add new recipes at the top of the list instead at the end.
- If a recipe is added where the url already is in the database it would be good to update the database entry instead of adding a duplicate.

2024-10-20 13:29 UTC, Jan0H0Punkt commented
> One important thing to change: imageUrl/image should be the same in frontend and backend.
> 
> Other issues that could go into another task:
> 
> * Once a recipe is added it would be good to see the added recipe in the list. Now a manual refresh is needed to see the new recipe inserted into the list.
> * I would add new recipes at the top of the list instead at the end.
> * If a recipe is added where the url already is in the database it would be good to update the database entry instead of adding a duplicate.

- I change the image to imageUrl in the backend because at the moment we save the url and not an img.
- The recipe is shown directly without refresh already. Maybe the something was slow in your case?
- i will change it so the latest added item will be the first
- the duplication thing is a feature request in my opinion. Because we also have to communicate that we change existing data to the user. I will create an item for it.

2024-10-28 19:25 UTC, crookoo approved these changes

2024-10-28 19:25 UTC, merged